server:
  port: ${APP_PORT:8080}
  shutdown: graceful
  servlet:
    context-path: /v1

spring:
  application:
    name: kafka-lab

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

otel:
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  exporter:
    otlp:
      endpoint: ${OTEL_COLLECTOR_ENDPOINT:http://minikube:31778}
